name: AndrewThomas
favicon: null
layout_spectrum: 0.19868
typography_spectrum: 0.41633
title: Andrew Thomas Fine Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202521'
    - '#4a433b'
    - '#816a6d'
    - '#cd7f6e'
    - '#f5bcaa'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
